### ISSUE TITLE
Temp Delete

### ISSUE THREAD

**Issue by JimSEOW** [adamped/Instagram#1]
Come later

**Comment by adamped** [comment]
@JimSEOW - I  know you deleted the message, but couldn't find your email, hence just replying here.

The Exrin framework itself, hasn't gone back or changed in what it can do, or how it can be structured, I suppose my examples have.

Exrin QuickStart, is what I mainly use for examples, as it's too much effort to do the entire project structure for demo code. But its certainly not what I would recommend for production apps.

Exrin Standard (what you see in the video's etc) - are the preferred way to structure your app. I recommend this approach for most people.

Exrin Isolates - are for huge apps and teams, and aren't going to be used that often.

In regards to the folder structure, this is really just cosmetic. There is no underlying differences. I do apologize that I should have been a bit quicker coming forward and in my examples to show how I structure real life app using the Feature Grouping approach. 

When I was creating examples, I was in the mindset of showing the features of Exrin and how it's stuck together at a quick glance. Feature Grouping is luckily only a folder switch up, no architectural or structural changes are needed to your app to support it, just move folders around.

Apologies for not sending through a clear enough message in my examples but I hope this message clears it up. 

You are on the right track with your project structure (the standard way), and you may want to switch your folder structure up to feature grouping, but that is completely optional and doesn't have any effect on the actual operation of your app, it's just how your solution explorer will look.

Also I am continuing to learn myself, I don't know everything. I might discover more awesome things down the line, that I will want to share :)

**Comment by JimSEOW** [comment]
@adamped I just clone the latest Exrin and bring everything to .NET standards 1.4. I am VERY positive with Exrin. I have more to feedback. 

You are pioneering Hierarchical View and this is the biggest differentiation for Exrin MVVM. You need time to sort out HOW to standardize the naming convention, how to template your use case for dissemination and a greater adoption among the XF developers.
