### ISSUE TITLE
VS2017 Compile Error Android Project

### ISSUE THREAD

**Issue by ThomasGugler** [adamped/Instagram#2]
Android Project, rebuild, build....cannot get rid of:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.	Instagram.Android	C:\Projects\Samples\Instagram-master\Instagram\Instagram.Android\obj\Debug\__library_projects__\Xamarin.Android.Support.v7.AppCompat\library_project_imports\res\values-v24\values-v24.xml	2	

Severity	Code	Description	Project	File	Line	Suppression State
Error		Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.	Instagram.Android	C:\Projects\Samples\Instagram-master\Instagram\Instagram.Android\obj\Debug\__library_projects__\Xamarin.Android.Support.v7.AppCompat\library_project_imports\res\values-v24\values-v24.xml	2

**Comment by adamped** [comment]
Its likely you don't have the latest build tools installed. Open the Android SDK manager, and install the latest stable SDK and build tools.
